"""add tags advice pi ac dc columns

Revision ID: 57c602bc5da0
Revises: 
Create Date: 2026-02-28 23:02:34.098902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c602bc5da0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('pi', sa.Float(), nullable=True))
    op.add_column('analysis_results', sa.Column('ac', sa.Float(), nullable=True))
    op.add_column('analysis_results', sa.Column('dc', sa.Float(), nullable=True))
    op.add_column('measurements', sa.Column('advice', sa.Text(), nullable=True))
    op.add_column('measurements', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('has_diabetes', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_profile_complete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_profile_complete')
    op.drop_column('users', 'has_diabetes')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'height')
    op.drop_column('measurements', 'tags')
    op.drop_column('measurements', 'advice')
    op.drop_column('analysis_results', 'dc')
    op.drop_column('analysis_results', 'ac')
    op.drop_column('analysis_results', 'pi')
    # ### end Alembic commands ###
